test workflow runs on pr

diff --git a/.github/workflows/child-workflow.yml b/.github/workflows/child-workflow.yml
--- a/.github/workflows/child-workflow.yml
+++ b/.github/workflows/child-workflow.yml
@@ -35,5 +35,5 @@ jobs:
         if: ${{ contains(inputs.changes, 'src/onlychild') }}
         run: echo "i modified my only child"
         
-      - name: "lets fail"
-        run: exit 1
+      # - name: "lets fail"
+      #   run: exit 1
